
import { useAffiliate } from "@/contexts/AffiliateContext";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { StatsCard } from "@/components/StatsCard";
import { DollarSign, Users, TrendingUp, Target } from "lucide-react";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from "@/components/ui/table";

export const AdminOverview = () => {
  const { affiliateOverviews, isLoading } = useAffiliate();

  // Calculate admin-level aggregated metrics
  const totalCommission = affiliateOverviews.reduce((sum, affiliate) => sum + (affiliate.totalCommission || 0), 0);
  const totalSales = affiliateOverviews.reduce((sum, affiliate) => sum + (affiliate.totalSales || 0), 0);
  const totalCustomers = affiliateOverviews.reduce((sum, affiliate) => sum + (affiliate.customerCount || 0), 0);
  const averageCommissionRate = affiliateOverviews.length > 0 
    ? affiliateOverviews.reduce((sum, affiliate) => sum + affiliate.commissionRate, 0) / affiliateOverviews.length 
    : 0;

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-semibold tracking-tight">Admin Overview</h2>
        <p className="text-muted-foreground">
          Complete overview of all affiliate performance and system metrics
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <StatsCard
          title="Total Network Commission"
          value={`$${totalCommission.toFixed(2)}`}
          description="Total earned across all affiliates"
          icon={<DollarSign className="w-4 h-4" />}
          className="bg-primary/5"
        />
        <StatsCard
          title="Total Network Sales"
          value={`$${totalSales.toFixed(2)}`}
          description="Total revenue generated by affiliates"
          icon={<TrendingUp className="w-4 h-4" />}
        />
        <StatsCard
          title="Total Customers"
          value={totalCustomers}
          description="Total customers across all affiliates"
          icon={<Users className="w-4 h-4" />}
        />
        <StatsCard
          title="Avg Commission Rate"
          value={`${(averageCommissionRate * 100).toFixed(1)}%`}
          description="Average commission rate across affiliates"
          icon={<Target className="w-4 h-4" />}
        />
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Affiliate Performance Summary</CardTitle>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="flex items-center justify-center py-8">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
            </div>
          ) : affiliateOverviews.length > 0 ? (
            <div className="border rounded-md overflow-hidden">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Affiliate</TableHead>
                    <TableHead>Code</TableHead>
                    <TableHead>Commission Rate</TableHead>
                    <TableHead className="text-right">Total Sales</TableHead>
                    <TableHead className="text-right">Total Commission</TableHead>
                    <TableHead className="text-right">Customers</TableHead>
                    <TableHead className="text-right">Performance</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {affiliateOverviews.map((affiliate, i) => (
                    <TableRow key={i}>
                      <TableCell className="font-medium">{affiliate.email}</TableCell>
                      <TableCell>
                        <span className="px-2 py-1 bg-secondary rounded text-sm">
                          {affiliate.affiliateCode}
                        </span>
                      </TableCell>
                      <TableCell>{(affiliate.commissionRate * 100).toFixed(0)}%</TableCell>
                      <TableCell className="text-right">${affiliate.totalSales?.toFixed(2) || "0.00"}</TableCell>
                      <TableCell className="text-right font-medium">${affiliate.totalCommission?.toFixed(2) || "0.00"}</TableCell>
                      <TableCell className="text-right">{affiliate.customerCount || 0}</TableCell>
                      <TableCell className="text-right">
                        <div className="flex items-center justify-end gap-2">
                          <div className={`w-2 h-2 rounded-full ${
                            (affiliate.totalSales || 0) > 1000 ? 'bg-green-500' :
                            (affiliate.totalSales || 0) > 100 ? 'bg-yellow-500' : 'bg-red-500'
                          }`} />
                          <span className="text-sm text-muted-foreground">
                            {(affiliate.totalSales || 0) > 1000 ? 'High' :
                             (affiliate.totalSales || 0) > 100 ? 'Medium' : 'Low'}
                          </span>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          ) : (
            <div className="text-center py-8 text-muted-foreground">
              No affiliate data available.
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};
