
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { StatsCard } from "@/components/StatsCard";
import { CommissionTable } from "@/components/CommissionTable";
import { MonthlyCommissionChart } from "@/components/MonthlyCommissionChart";
import { DollarSign, Users, TrendingUp, Target } from "lucide-react";
import { useAffiliate } from "@/contexts/AffiliateContext";
import { AffiliateSelector } from "./AffiliateSelector";
import { filterCommissions } from "@/utils/affiliateUtils";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from "@/components/ui/table";

export const AdminDashboardView = () => {
  const { affiliateOverviews, commissions, summary } = useAffiliate();
  const [selectedAffiliate, setSelectedAffiliate] = useState<string | null>(null);

  // Filter out admin from affiliate overviews - admin is not an affiliate
  const realAffiliates = affiliateOverviews.filter(affiliate => 
    affiliate.affiliateCode !== 'admin' && 
    affiliate.email !== 'admin@whaamkabaam.com'
  );

  // Get filtered data based on selected affiliate
  const getFilteredData = () => {
    if (!selectedAffiliate) {
      // Return aggregated data for all real affiliates only
      const totalCommission = realAffiliates.reduce((sum, affiliate) => sum + (affiliate.totalCommission || 0), 0);
      const totalSales = realAffiliates.reduce((sum, affiliate) => sum + (affiliate.totalSales || 0), 0);
      const totalCustomers = realAffiliates.reduce((sum, affiliate) => sum + (affiliate.customerCount || 0), 0);
      
      return {
        totalCommission,
        totalSales,
        customerCount: totalCustomers,
        commissions: commissions
      };
    } else {
      // Return data for specific affiliate
      const filteredCommissions = filterCommissions(commissions, selectedAffiliate);
      const affiliate = realAffiliates.find(a => a.affiliateCode === selectedAffiliate);
      
      return {
        totalCommission: affiliate?.totalCommission || 0,
        totalSales: affiliate?.totalSales || 0,
        customerCount: affiliate?.customerCount || 0,
        commissions: filteredCommissions
      };
    }
  };

  const filteredData = getFilteredData();

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-semibold tracking-tight">
            {selectedAffiliate ? `${selectedAffiliate} Dashboard View` : "Affiliate Network Overview"}
          </h2>
          <p className="text-muted-foreground">
            {selectedAffiliate 
              ? `Viewing dashboard as it appears to ${selectedAffiliate}` 
              : "Complete overview of all affiliate performance"
            }
          </p>
        </div>
        <AffiliateSelector
          affiliates={realAffiliates}
          selectedAffiliate={selectedAffiliate}
          onAffiliateChange={setSelectedAffiliate}
        />
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <StatsCard
          title="Total Network Commission"
          value={`$${filteredData.totalCommission.toFixed(2)}`}
          description={selectedAffiliate ? "Total earned by this affiliate" : "Total across all affiliates"}
          icon={<DollarSign className="w-4 h-4" />}
          className="bg-primary/5"
        />
        <StatsCard
          title="Total Network Sales"
          value={`$${filteredData.totalSales.toFixed(2)}`}
          description={selectedAffiliate ? "Revenue generated by this affiliate" : "Total revenue across all affiliates"}
          icon={<TrendingUp className="w-4 h-4" />}
        />
        <StatsCard
          title="Total Customers"
          value={filteredData.customerCount}
          description={selectedAffiliate ? "Customers referred by this affiliate" : "Total customers across all affiliates"}
          icon={<Users className="w-4 h-4" />}
        />
        <StatsCard
          title="Active Affiliates"
          value={realAffiliates.length}
          description="Currently active affiliate partners"
          icon={<Target className="w-4 h-4" />}
        />
      </div>

      <div className="grid gap-4">
        <MonthlyCommissionChart />
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Affiliate Performance Dashboard</CardTitle>
        </CardHeader>
        <CardContent>
          {realAffiliates.length > 0 ? (
            <div className="border rounded-md overflow-hidden">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Affiliate</TableHead>
                    <TableHead>Code</TableHead>
                    <TableHead>Commission Rate</TableHead>
                    <TableHead className="text-right">Total Sales</TableHead>
                    <TableHead className="text-right">Total Commission</TableHead>
                    <TableHead className="text-right">Customers</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {realAffiliates.map((affiliate, i) => (
                    <TableRow key={i}>
                      <TableCell className="font-medium">{affiliate.email}</TableCell>
                      <TableCell>
                        <span className="px-2 py-1 bg-secondary rounded text-sm">
                          {affiliate.affiliateCode}
                        </span>
                      </TableCell>
                      <TableCell>{(affiliate.commissionRate * 100).toFixed(0)}%</TableCell>
                      <TableCell className="text-right">${affiliate.totalSales?.toFixed(2) || "0.00"}</TableCell>
                      <TableCell className="text-right font-medium">${affiliate.totalCommission?.toFixed(2) || "0.00"}</TableCell>
                      <TableCell className="text-right">{affiliate.customerCount || 0}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          ) : (
            <div className="text-center py-8 text-muted-foreground">
              No affiliate data available.
            </div>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>
            {selectedAffiliate ? `${selectedAffiliate} Recent Transactions` : "All Network Transactions"}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <CommissionTable limit={10} />
        </CardContent>
      </Card>
    </div>
  );
};
