// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjgxnrmndfadrbolvdrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqZ3hucm1uZGZhZHJib2x2ZHJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyODE3OTYsImV4cCI6MjA1Njg1Nzc5Nn0.Mr4qe48_kXX__SRcnYs6awd-7hQqcm67581GM_cHyks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);