
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { AffiliateRpcResponse } from '@/types/supabase';

const SUPABASE_URL = "https://xfkkmkxeoqawqnvahhoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhma2tta3hlb3Fhd3FudmFoaG9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NTIxNjAsImV4cCI6MjA2MzUyODE2MH0.FEM3uhXSTXgx7Ro3vbG9q8PLqPohDsg8IX8ELH6Rm70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Type definitions
export type AppRole = 'admin' | 'affiliate';

export interface Affiliate {
  id: string;
  affiliate_code: string;
  commission_rate: number;
  user_id: string;
  created_at: string;
}

// Define interface for the JSON response from admin_get_affiliates
export interface AffiliateJson {
  id: string;
  user_id: string;
  email: string;
  affiliate_code: string;
  commission_rate: number;
  total_commission: number;
  total_sales: number;
  customer_count: number;
  created_at: string;
}

// Add interface for affiliate data from RPC function
export interface AffiliateData {
  affiliate_code?: string;
  commission_rate?: number;
}

// RPC function return type helpers
export interface RpcResponse<T> {
  data: T | null;
  error: Error | null;
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
