
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjgxnrmndfadrbolvdrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqZ3hucm1uZGZhZHJib2x2ZHJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyODE3OTYsImV4cCI6MjA1Njg1Nzc5Nn0.Mr4qe48_kXX__SRcnYs6awd-7hQqcm67581GM_cHyks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
});

// Helper types to work with tables missing from auto-generated types
export type UserRole = {
  id: string;
  user_id: string;
  role: AppRole;
  created_at: string;
}

export type Affiliate = {
  id: string;
  affiliate_code: string;
  commission_rate: number;
  created_at: string;
  updated_at: string;
}

export type Commission = {
  id: string;
  affiliate_id: string;
  customer_id: string;
  amount: number;
  total_sale: number;
  product_id?: string;
  transaction_date: string;
  status: string;
  payment_id?: string;
}

export type Customer = {
  id: string;
  email: string;
  referred_by: string;
  created_at: string;
}

export type AppRole = 'admin' | 'affiliate';

// Add extension for Supabase with RPC functions to help with TypeScript errors
declare module '@supabase/supabase-js' {
  interface SupabaseClient<Database = any> {
    rpc<T = any>(
      fn: string,
      params?: object,
      options?: {
        head?: boolean;
        count?: 'exact' | 'planned' | 'estimated';
      }
    ): Promise<{
      data: T;
      error: Error | null;
    }>;
  }
}
